---
apiVersion: kafka.eda.nokia.com/v1
kind: Producer
metadata:
  name: alarms-and-deviations
  namespace: eda
spec:
  brokers: kafka.eda.svc.cluster.local:9092
  exports:
    - path: .namespace.alarms.v1.alarm
      topic: alarms
      mode: onChange
    - path: .namespace.resources.cr.core_eda_nokia_com.v1.deviation
      topic: deviations
      mode: onChange
