apiVersion: fabrics.eda.nokia.com/v1
kind: Fabric
metadata:
  name: myfabric
  namespace: eda-telemetry
spec:
  interSwitchLinks:
    ipMTU: 9200
    linkSelectors:
      - eda.nokia.com/role=interSwitch
    unnumbered: IPv6
  leafs:
    leafNodeSelectors:
      - eda.nokia.com/role=leaf
  overlayProtocol:
    bgp: {}
    protocol: EBGP
  spines:
    spineNodeSelectors:
      - eda.nokia.com/role=spine
  systemPoolIPv4: systemipv4-pool
  underlayProtocol:
    bgp:
      asnPool: asn-pool
    protocols:
      - EBGP

