apiVersion: topologies.eda.nokia.com/v1
kind: NetworkTopology
metadata:
  name: my-topology
  namespace: eda
spec:
  operation: ReplaceAll
  nodeTemplates:
    - name: leaf
      nodeProfile: srlinux-ghcr-25.10.1
      platform: 7220 IXR-D2L
      labels:
        eda.nokia.com/security-profile: managed
        eda.nokia.com/role: leaf
    - name: spine
      nodeProfile: srlinux-ghcr-25.10.1
      platform: 7220 IXR-D3L
      labels:
        eda.nokia.com/security-profile: managed
        eda.nokia.com/role: spine
    - name: rail
      nodeProfile: srlinux-ghcr-25.10.1
      platform: 7220 IXR-H5-32D
      labels:
        eda.nokia.com/security-profile: managed
        eda.nokia.com/role: rail
  nodes:
    - name: leaf1
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "15"
        topobuilder.eda.labs/y: "405"
    - name: leaf2
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "405"
        topobuilder.eda.labs/y: "405"
    - name: leaf3
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "615"
        topobuilder.eda.labs/y: "405"
    - name: leaf4
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "1005"
        topobuilder.eda.labs/y: "405"
    - name: spine1
      template: spine
      annotations:
        topobuilder.eda.labs/x: "255"
        topobuilder.eda.labs/y: "795"
    - name: spine2
      template: spine
      annotations:
        topobuilder.eda.labs/x: "675"
        topobuilder.eda.labs/y: "765"
    - name: rail1
      template: rail
      annotations:
        topobuilder.eda.labs/x: "135"
        topobuilder.eda.labs/y: "-450"
    - name: rail2
      template: rail
      annotations:
        topobuilder.eda.labs/x: "825"
        topobuilder.eda.labs/y: "-435"
  linkTemplates:
    - name: isl
      type: InterSwitch
      labels:
        eda.nokia.com/role: interSwitch
    - name: edge
      type: Edge
      encapType: Dot1q
      labels:
        eda.nokia.com/role: edge
        eda.nokia.com/macvrf1001: "true"
    - name: gpu-edge
      type: Edge
      encapType: Dot1q
      labels:
        eda.nokia.com/role: gpu-edge
  links:
    - name: leaf1-spine1
      annotations:
        topobuilder.eda.labs/edgeId: edge-42
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-49
          remote:
            node: spine1
            interface: ethernet-1-1
      template: isl
    - name: leaf1-spine2
      annotations:
        topobuilder.eda.labs/edgeId: edge-43
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-50
          remote:
            node: spine2
            interface: ethernet-1-1
      template: isl
    - name: leaf2-spine1
      annotations:
        topobuilder.eda.labs/edgeId: edge-44
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf2
            interface: ethernet-1-49
          remote:
            node: spine1
            interface: ethernet-1-2
      template: isl
    - name: leaf2-spine2
      annotations:
        topobuilder.eda.labs/edgeId: edge-45
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf2
            interface: ethernet-1-50
          remote:
            node: spine2
            interface: ethernet-1-2
      template: isl
    - name: leaf3-spine1
      annotations:
        topobuilder.eda.labs/edgeId: edge-46
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-49
          remote:
            node: spine1
            interface: ethernet-1-3
      template: isl
    - name: leaf3-spine2
      annotations:
        topobuilder.eda.labs/edgeId: edge-47
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-50
          remote:
            node: spine2
            interface: ethernet-1-3
      template: isl
    - name: leaf4-spine1
      annotations:
        topobuilder.eda.labs/edgeId: edge-48
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-49
          remote:
            node: spine1
            interface: ethernet-1-4
      template: isl
    - name: leaf4-spine2
      annotations:
        topobuilder.eda.labs/edgeId: edge-49
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-50
          remote:
            node: spine2
            interface: ethernet-1-4
      template: isl
    - name: rail1-svr-1-gpu1
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-50
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail1
            interface: ethernet-1-1
          sim:
            simNode: server1
            simNodeInterface: eth11
    - name: rail2-svr-1-gpu2
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-51
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail2
            interface: ethernet-1-1
          sim:
            simNode: server1
            simNodeInterface: eth12
    - name: rail1-svr-2-gpu1
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-52
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail1
            interface: ethernet-1-2
          sim:
            simNode: server2
            simNodeInterface: eth11
    - name: rail2-svr-2-gpu2
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-53
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail2
            interface: ethernet-1-2
          sim:
            simNode: server2
            simNodeInterface: eth12
    - name: rail1-svr-3-gpu1
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-54
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail1
            interface: ethernet-1-3
          sim:
            simNode: server3
            simNodeInterface: eth11
    - name: rail2-svr-3-gpu2
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-55
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail2
            interface: ethernet-1-3
          sim:
            simNode: server3
            simNodeInterface: eth12
    - name: rail1-svr-4-gpu1
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-56
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail1
            interface: ethernet-1-4
          sim:
            simNode: server4
            simNodeInterface: eth11
    - name: rail2-svr-4-gpu2
      template: gpu-edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-57
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: rail2
            interface: ethernet-1-4
          sim:
            simNode: server4
            simNodeInterface: eth12
    - name: l1-l2-e1-1-lag-1
      labels:
        eda.nokia.com/macvrf201: "true"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-1
          sim:
            simNode: server1
            simNodeInterface: eth1
        - local:
            node: leaf2
            interface: ethernet-1-1
          sim:
            simNode: server1
            simNodeInterface: eth2
      template: edge
    - name: l1-l2-e1-2-lag-2
      labels:
        eda.nokia.com/macvrf202: "true"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-2
          sim:
            simNode: server2
            simNodeInterface: eth1
        - local:
            node: leaf2
            interface: ethernet-1-2
          sim:
            simNode: server2
            simNodeInterface: eth2
      template: edge
    - name: l3-l4-e1-1-lag-1
      labels:
        eda.nokia.com/macvrf201: "true"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-1
          sim:
            simNode: server3
            simNodeInterface: eth1
        - local:
            node: leaf4
            interface: ethernet-1-1
          sim:
            simNode: server3
            simNodeInterface: eth2
      template: edge
    - name: l3-l4-e1-2-lag-2
      labels:
        eda.nokia.com/macvrf202: "true"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-2
          sim:
            simNode: server4
            simNodeInterface: eth1
        - local:
            node: leaf4
            interface: ethernet-1-2
          sim:
            simNode: server4
            simNodeInterface: eth2
      template: edge
  simulation:
    simNodeTemplates:
      - name: multitool
        type: Linux
        image: ghcr.io/mfzhsn/network-multitool-roce:0.1
    simNodes:
      - name: server1
        template: multitool
        annotations:
          topobuilder.eda.labs/x: "30"
          topobuilder.eda.labs/y: "-45"
      - name: server2
        template: multitool
        annotations:
          topobuilder.eda.labs/x: "330"
          topobuilder.eda.labs/y: "45"
      - name: server3
        template: multitool
        annotations:
          topobuilder.eda.labs/x: "615"
          topobuilder.eda.labs/y: "-75"
      - name: server4
        template: multitool
        annotations:
          topobuilder.eda.labs/x: "945"
          topobuilder.eda.labs/y: "45"
 
