---
anchors:
  thresholds-operstate: &thresholds-operstate
  - color: red
    level: 0
  - color: green
    level: 1
  thresholds-traffic: &thresholds-traffic
  - color: gray
    level: 0
  - color: green
    level: 199999
  - color: yellow
    level: 500000
  - color: orange
    level: 1000000
  - color: red
    level: 5000000
  label-config: &label-config
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
    - valueMax: 199999
      text: ​
    - valueMin: 200000
cellIdPreamble: cell-
cells:
  leaf1:ethernet-1/49:spine1:ethernet-1/1:
    dataRef: oper-state:leaf1:ethernet-1/49
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf1:ethernet-1/49:spine1:ethernet-1/1:
    dataRef: leaf1:ethernet-1/49:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf1:ethernet-1/50:spine2:ethernet-1/1:
    dataRef: oper-state:leaf1:ethernet-1/50
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf1:ethernet-1/50:spine2:ethernet-1/1:
    dataRef: leaf1:ethernet-1/50:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf1:ethernet-1/1:server1:eth1:
    dataRef: oper-state:leaf1:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf1:ethernet-1/1:server1:eth1:
    dataRef: leaf1:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf1:ethernet-1/2:server2:eth1:
    dataRef: oper-state:leaf1:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf1:ethernet-1/2:server2:eth1:
    dataRef: leaf1:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf2:ethernet-1/49:spine1:ethernet-1/2:
    dataRef: oper-state:leaf2:ethernet-1/49
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf2:ethernet-1/49:spine1:ethernet-1/2:
    dataRef: leaf2:ethernet-1/49:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf2:ethernet-1/50:spine2:ethernet-1/2:
    dataRef: oper-state:leaf2:ethernet-1/50
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf2:ethernet-1/50:spine2:ethernet-1/2:
    dataRef: leaf2:ethernet-1/50:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf2:ethernet-1/1:server1:eth2:
    dataRef: oper-state:leaf2:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf2:ethernet-1/1:server1:eth2:
    dataRef: leaf2:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf2:ethernet-1/2:server2:eth2:
    dataRef: oper-state:leaf2:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf2:ethernet-1/2:server2:eth2:
    dataRef: leaf2:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf3:ethernet-1/49:spine1:ethernet-1/3:
    dataRef: oper-state:leaf3:ethernet-1/49
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf3:ethernet-1/49:spine1:ethernet-1/3:
    dataRef: leaf3:ethernet-1/49:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf3:ethernet-1/50:spine2:ethernet-1/3:
    dataRef: oper-state:leaf3:ethernet-1/50
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf3:ethernet-1/50:spine2:ethernet-1/3:
    dataRef: leaf3:ethernet-1/50:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf3:ethernet-1/1:server3:eth1:
    dataRef: oper-state:leaf3:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf3:ethernet-1/1:server3:eth1:
    dataRef: leaf3:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf3:ethernet-1/2:server4:eth1:
    dataRef: oper-state:leaf3:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf3:ethernet-1/2:server4:eth1:
    dataRef: leaf3:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf4:ethernet-1/49:spine1:ethernet-1/4:
    dataRef: oper-state:leaf4:ethernet-1/49
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf4:ethernet-1/49:spine1:ethernet-1/4:
    dataRef: leaf4:ethernet-1/49:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf4:ethernet-1/50:spine2:ethernet-1/4:
    dataRef: oper-state:leaf4:ethernet-1/50
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf4:ethernet-1/50:spine2:ethernet-1/4:
    dataRef: leaf4:ethernet-1/50:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf4:ethernet-1/1:server3:eth2:
    dataRef: oper-state:leaf4:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf4:ethernet-1/1:server3:eth2:
    dataRef: leaf4:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf4:ethernet-1/2:server4:eth2:
    dataRef: oper-state:leaf4:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:leaf4:ethernet-1/2:server4:eth2:
    dataRef: leaf4:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine1:ethernet-1/1:leaf1:ethernet-1/49:
    dataRef: oper-state:spine1:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:ethernet-1/1:leaf1:ethernet-1/49:
    dataRef: spine1:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine1:ethernet-1/2:leaf2:ethernet-1/49:
    dataRef: oper-state:spine1:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:ethernet-1/2:leaf2:ethernet-1/49:
    dataRef: spine1:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine1:ethernet-1/3:leaf3:ethernet-1/49:
    dataRef: oper-state:spine1:ethernet-1/3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:ethernet-1/3:leaf3:ethernet-1/49:
    dataRef: spine1:ethernet-1/3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine1:ethernet-1/4:leaf4:ethernet-1/49:
    dataRef: oper-state:spine1:ethernet-1/4
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:ethernet-1/4:leaf4:ethernet-1/49:
    dataRef: spine1:ethernet-1/4:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:ethernet-1/1:leaf1:ethernet-1/50:
    dataRef: oper-state:spine2:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:ethernet-1/1:leaf1:ethernet-1/50:
    dataRef: spine2:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:ethernet-1/2:leaf2:ethernet-1/50:
    dataRef: oper-state:spine2:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:ethernet-1/2:leaf2:ethernet-1/50:
    dataRef: spine2:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:ethernet-1/3:leaf3:ethernet-1/50:
    dataRef: oper-state:spine2:ethernet-1/3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:ethernet-1/3:leaf3:ethernet-1/50:
    dataRef: spine2:ethernet-1/3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:ethernet-1/4:leaf4:ethernet-1/50:
    dataRef: oper-state:spine2:ethernet-1/4
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:ethernet-1/4:leaf4:ethernet-1/50:
    dataRef: spine2:ethernet-1/4:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail1:ethernet-1/1:server1:eth11:
    dataRef: oper-state:rail1:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail1:ethernet-1/1:server1:eth11:
    dataRef: rail1:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail1:ethernet-1/2:server2:eth11:
    dataRef: oper-state:rail1:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail1:ethernet-1/2:server2:eth11:
    dataRef: rail1:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail1:ethernet-1/3:server3:eth11:
    dataRef: oper-state:rail1:ethernet-1/3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail1:ethernet-1/3:server3:eth11:
    dataRef: rail1:ethernet-1/3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail1:ethernet-1/4:server4:eth11:
    dataRef: oper-state:rail1:ethernet-1/4
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail1:ethernet-1/4:server4:eth11:
    dataRef: rail1:ethernet-1/4:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail2:ethernet-1/1:server1:eth12:
    dataRef: oper-state:rail2:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail2:ethernet-1/1:server1:eth12:
    dataRef: rail2:ethernet-1/1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail2:ethernet-1/2:server2:eth12:
    dataRef: oper-state:rail2:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail2:ethernet-1/2:server2:eth12:
    dataRef: rail2:ethernet-1/2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail2:ethernet-1/3:server3:eth12:
    dataRef: oper-state:rail2:ethernet-1/3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail2:ethernet-1/3:server3:eth12:
    dataRef: rail2:ethernet-1/3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rail2:ethernet-1/4:server4:eth12:
    dataRef: oper-state:rail2:ethernet-1/4
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rail2:ethernet-1/4:server4:eth12:
    dataRef: rail2:ethernet-1/4:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server1:eth1:leaf1:ethernet-1/1:
    dataRef: oper-state:server1:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server1:eth1:leaf1:ethernet-1/1:
    dataRef: server1:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server1:eth2:leaf2:ethernet-1/1:
    dataRef: oper-state:server1:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server1:eth2:leaf2:ethernet-1/1:
    dataRef: server1:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server1:eth11:rail1:ethernet-1/1:
    dataRef: oper-state:server1:eth11
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server1:eth11:rail1:ethernet-1/1:
    dataRef: server1:eth11:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server1:eth12:rail2:ethernet-1/1:
    dataRef: oper-state:server1:eth12
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server1:eth12:rail2:ethernet-1/1:
    dataRef: server1:eth12:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server2:eth1:leaf1:ethernet-1/2:
    dataRef: oper-state:server2:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server2:eth1:leaf1:ethernet-1/2:
    dataRef: server2:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server2:eth2:leaf2:ethernet-1/2:
    dataRef: oper-state:server2:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server2:eth2:leaf2:ethernet-1/2:
    dataRef: server2:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server2:eth11:rail1:ethernet-1/2:
    dataRef: oper-state:server2:eth11
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server2:eth11:rail1:ethernet-1/2:
    dataRef: server2:eth11:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server2:eth12:rail2:ethernet-1/2:
    dataRef: oper-state:server2:eth12
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server2:eth12:rail2:ethernet-1/2:
    dataRef: server2:eth12:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server3:eth1:leaf3:ethernet-1/1:
    dataRef: oper-state:server3:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server3:eth1:leaf3:ethernet-1/1:
    dataRef: server3:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server3:eth2:leaf4:ethernet-1/1:
    dataRef: oper-state:server3:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server3:eth2:leaf4:ethernet-1/1:
    dataRef: server3:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server3:eth11:rail1:ethernet-1/3:
    dataRef: oper-state:server3:eth11
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server3:eth11:rail1:ethernet-1/3:
    dataRef: server3:eth11:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server3:eth12:rail2:ethernet-1/3:
    dataRef: oper-state:server3:eth12
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server3:eth12:rail2:ethernet-1/3:
    dataRef: server3:eth12:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server4:eth1:leaf3:ethernet-1/2:
    dataRef: oper-state:server4:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server4:eth1:leaf3:ethernet-1/2:
    dataRef: server4:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server4:eth2:leaf4:ethernet-1/2:
    dataRef: oper-state:server4:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server4:eth2:leaf4:ethernet-1/2:
    dataRef: server4:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server4:eth11:rail1:ethernet-1/4:
    dataRef: oper-state:server4:eth11
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server4:eth11:rail1:ethernet-1/4:
    dataRef: server4:eth11:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  server4:eth12:rail2:ethernet-1/4:
    dataRef: oper-state:server4:eth12
    fillColor:
      thresholds: *thresholds-operstate
  link_id:server4:eth12:rail2:ethernet-1/4:
    dataRef: server4:eth12:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
